### ISSUE TITLE
SNHU New Integrated Grading and Rubric

### ISSUE THREAD

**Issue by mbenz570** [mattkearl/brightspacespeedgrader#2]
Matt,
Looks like snhu updated the textbox editor and now the plugin cannot find it. Do you know how to fix this? I tried just doing an edit to the iframe in your code for feedback but it did not work.

<iframe id="d2l-uid-35_ifr" frameborder="0" allowtransparency="true" title="Overall Feedback" class="tox-edit-area__iframe"></iframe>

**Comment by mattkearl** [comment]
SNHU broke everything on the last update (and the discussions are changing soon too and will be broken). I had to rewrite everything from the ground up (it took me 4 solid days) and even still it is buggy (I might do some more rewrites). I haven't posted anything or published it yet. I'm not sure I will either.

**Comment by mbenz570** [comment]
Can you post a snippet of code on how you are able to get the iframe? I like tinkering but still cant figure out why it isnt getting the iframe.

**Comment by mattkearl** [comment]
Everything was new. I literally had to scrap all old code and rewrite the thing 100% (other than the discussions, they still work). So I don't think any new snippets will work. I am considering selling it once I get it going fully because it has just taken so much time to make.

**Comment by mbenz570** [comment]
Matt,
Thanks for the quick response, i was able to get it working. Thanks!
